### ISSUE TITLE
lumi doesn't work on Windows

### ISSUE THREAD

**Issue by BeniaminK** [Tanmoy741127/lumi#15]
Gunicorn doesn't support Windows which restricts also `lumi` framework.
Maybe there should be considered any other WSGI server implementation, e.g. `waitress` which works well on other OSes?

**Comment by Tanmoy741127** [comment]
Yes the gunicorn is available on linux actually.  I will add another wsgi
client for windows next week. This week I am actually busy.

**Comment by Tanmoy741127** [comment]
Hi @ffreemt added support for windows. Give it a try. If you faced any issue please let me know.

**Comment by ffreemt** [comment]
Cool! I'll give it a spin.

**Comment by ffreemt** [comment]
It works great in win10 👍 !

Is it possible to somehow turn on debug/verbose mode (to show more messages from the server)?

When I run `python app.py`, all I get is 
```
🚀 Running development server at http://127.0.0.1:8080
```
and nothing else, even when I make successful http requests to 27.0.0.1:8080.

**Comment by Tanmoy741127** [comment]
Yep ! Working on that. Most probably available tomorrow with File Sharing
support.

**Comment by Tanmoy741127** [comment]
@ffreemt Now you can give it a try, It has now debug mode which provide better logging. Check the [README.MD](https://github.com/Tanmoy741127/lumi/blob/main/README.md) for better understanding.

**Comment by tanmoysrt** [comment]
As this issue resolved, closing this issue !
Thanks @ffreemt  and @BeniaminK  for creating the issues.
