### ISSUE TITLE
GET Or PUT Methods 

### ISSUE THREAD

**Issue by AmirMGhanem** [Tanmoy741127/lumi#2]
first of all i like the idea of the project. 
how do you deal with method types?

**Comment by AmirMGhanem** [comment]
Support for method type can be done on the app.register level. which the user can provide the method type and the server api will behave according the user method request.

**Comment by Tanmoy741127** [comment]
Yes, I got that, but there is an issue with only getting requests due to the dynamic typing of python.

Suppose a function signature is
```
add(a, b)
```
Now in the function, the `a` can be int, float, string, or anything. So when I call the process, I need to know beforehand what is arguments required by that function.

One solution is that I also take argument type from the user, But I want to avoid that by default

Please share if you have any idea how we can solve the issue.

**Comment by Tanmoy741127** [comment]
Hey, what do you think if I just allow the GET  request for those functions that do not require any arguments /

**Comment by AmirMGhanem** [comment]
Hi, 
Can be a good temporarily solution for now.
it will be nice if we ask the users to define the argument and the arg type.

**Comment by AmirMGhanem** [comment]
`{'/add': {'default_values': {},
          'file_name': 'test.py',
          'key': 'Muh_ORVKeS',
          'module_name': '__main__',
          'name': 'add',
          'parameters': {'all': ['a', 'b'],
                         'optional': [],
                         'required': ['a', 'b']}},`


we can have parameters like key-value pair array. which will be like [{Arg1:Type1},{Arg12:Type2},{Arg3:Type3}]
and then we can check if the request method equals to the method type he registered for. and so on

**Comment by Tanmoy741127** [comment]
Ok! The main problem arises if the user wants to send a list of elements.
It does not make sense to pass a list in GET request query parameters.
But if the user wants, we need to handle that also
Let me check if we can retrieve the list if any user wants to change it.

**Comment by Tanmoy741127** [comment]
Today , will push update to a new branch for PUT request support.
Then seeing GET request.

**Comment by AmirMGhanem** [comment]
im trying to work on the GET at the moment. 
no success

**Comment by AmirMGhanem** [comment]
@Tanmoy741127 i saw ur push right now. i have some changes for the method types, let me pr and then u continue from there to the PUT

**Comment by Tanmoy741127** [comment]
That was an small change actually for json decoding issue.

I will continue to integrate PUT and PATCH in new branch. So no issue .

**Comment by AmirMGhanem** [comment]
pushed, PR rn

**Comment by Tanmoy741127** [comment]
ok

**Comment by Tanmoy741127** [comment]
@AmirMGhanem Can you check once? I am not seeing any open PR currently.

**Comment by AmirMGhanem** [comment]
pushed

**Comment by AmirMGhanem** [comment]
@Tanmoy741127 
i've added workflow and readme comment :) take a look 
thanks

**Comment by Tanmoy741127** [comment]
Keeping the PR on hold, need to update the dictionary format before adding new request methods.
Will update tongiht

**Comment by AmirMGhanem** [comment]
OK :)

**Comment by Tanmoy741127** [comment]
@AmirMGhanem I have updated the dictionary format and also integrated `PUT` and `PATCH` request types . Kindly check and update and submit the PR.

**Comment by AmirMGhanem** [comment]
will sync later tonight.

**Comment by Tanmoy741127** [comment]
OK 👍

**Comment by AmirMGhanem** [comment]
Which task should i take care of ?
What is ur priorities ?

**Comment by Tanmoy741127** [comment]
Currently, I am looking at the GET requests.

We need one in-built support in the library to serve the static files from a folder [maybe a `public` folder]. 
Like on a reserved route like `/public/<file_name>` will send the requested file, and we also need to protect it from a directory traversal attack.

If you want, you can start work on that part on a new branch.

**Comment by AmirMGhanem** [comment]
can you describe one more scenario on the usage of public folder for files?

**Comment by Tanmoy741127** [comment]
Lumi is fully conceptualised based on API, not any purpose to render/serve HTML files.

But during developing something, we were required to serve images, videos.
So , I want that, lumi to have an middleware inbuilt that can server files from a folder.

By default, it will not be available, but if the user wants he can enable.

Suppose, the folder structure of project be

|-- app.py
|--  public/
     |-- img/
          |-- sample1.png
          |-- sample2.png

So if the user requests , <URL>/public/img/sample1.png, he will get the img

So, it will be better to give a in-built support

Suppose, to enable this we create `ServeStatic` Middleware
The user can use this like

```python

from lumi import Lumi
from lumi.middleware import ServeStatic

app = Lumi()
app.use(ServeStatic)

"""
  other functions
"""

app.runServer()
```

we have to add 
- support to integrate middleware by method `.use()`
- need to develop the  `ServeStatic` middleware

**Comment by Abutahir12** [comment]
I went through this conversation, haven't gone through the code yet, but I'd like to contribute

**Comment by Tanmoy741127** [comment]
You are welcome to contribute @Abutahir12 . Go through the codebase, if you face any issue, feel free to ask questions

**Comment by Abutahir12** [comment]
Sure @Tanmoy741127

**Comment by tanmoysrt** [comment]
In latest updates, both the method has been implemented.
So closing this issue .
